# Generated by Django 4.0.1 on 2022-01-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, related_name='services', to='registration.Service'),
        ),
    ]
