# Generated by Django 4.0.1 on 2022-01-07 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_package_discount_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.service'),
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
