# Generated by Django 4.0.1 on 2022-01-07 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_profile_package_delete_package'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('-price',)},
        ),
    ]
